### ISSUE TITLE
enhancement : Language ?

### ISSUE THREAD

**Issue by MacNaab** [Bonkahe/DMmaps#10] opened 2020-11-16 14:35 UTC
I have already asked you if it was possible to add an option to have several languages and you replied that it was complicated.
I have created a site which is available in French or English and I use the jquery function 
``` JS
$('#ID').load('file.htm');
```
The trick is to create a div that will receive the text from the translation file.
You can see a render [here](https://macnaab.github.io/Random-Tables/) (you have to click on "Tables aléatoires" in the navbar at the top.) and see the source files [here](https://github.com/MacNaab/Random-Tables/tree/master/Tables).
Maybe you can also use this with your program?
If it seems possible to you, I could do a portage in French. Otherwise it does not matter.
Note: I ask you that I am thinking of making a video presentation of your program (in French), and I know that some spectators are anglophobic!

**Comment by Bonkahe** [comment] 2020-11-16 14:39
Lol, Hmm I can definitely look into it, the hard part honestly is the menus, they are not created in a normal fashion, and they can be very difficult to implement changes like that on it, let me do a bit more digging.

**Comment by MacNaab** [comment] 2020-11-16 14:57
If the menus are not translated, this is not very disturbing.
The only problem with this method is that you must constantly update all the translation files. (Quit leaving some parts in English while waiting). 

The most secure would be to add a database (one per language).
Load English database and then the language (this crushing English elements but allowing elements to be kept in English if they are not translated) but it is also the one that requires a total redesign.

**Comment by Bonkahe** [comment] 2020-11-16 16:26
Ok, so I implemented localization, and using an extension integrated to my google api key I'm able to auto translate to any language needed, that being said it is google translate, so if you would look over it and see if you can spot anything that is blatantly off?
Pushing out the update with auto localization.
I may at a later date make it so you can manually override the localization to specific local using he options menu, if you want this let me know and I'll put it in.

Everything to the right of the ":" is the french version of what's on the left. I'm gonna go cook breakfast now ^.^

[fr.txt](https://github.com/Bonkahe/DMmaps/files/5548085/fr.txt)

**Comment by MacNaab** [comment] 2020-11-16 18:06
Awesome! Great job! I have corrected errors except one (for which I no longer have the context):
`Just Nodes`
Here the French file: [fr.txt](https://github.com/Bonkahe/DMmaps/files/5548822/fr.txt)

I also noticed that during actions with the right click, text remains in English. Just like 'toolbox' (although it is one of the keywords).
![image](https://user-images.githubusercontent.com/61412526/99290250-55f2f000-283e-11eb-950e-51a8d94d137d.png)
![image](https://user-images.githubusercontent.com/61412526/99290892-4031fa80-283f-11eb-8b59-b179c0e74eb8.png)

Nevertheless excellent work! Enjoy your meal! You really deserve it

**Comment by Bonkahe** [comment] 2020-11-16 18:17
![image](https://user-images.githubusercontent.com/11287274/99291502-8d917600-2805-11eb-846a-15d5bbf8a989.png)
Hmmmm It's functional on my end I'm wondering what the issue is...

Hold on I might have an idea.

Edit:
Yea it's available on the build for me.
![image](https://user-images.githubusercontent.com/11287274/99291794-f547c100-2805-11eb-8a44-3ac9e832e401.png)
![image](https://user-images.githubusercontent.com/11287274/99291802-f842b180-2805-11eb-8897-2a63d912c06d.png)
So I am not sure what is up at all.

Also the meal was wonderful!

PS: the `Just Nodes` is if you select nodes and want to delete them, you have the option to delete the nodes and the documents, or just the nodes, leaving the documents attached to them without nodes.

**Comment by Bonkahe** [comment] 2020-11-16 18:30
I also found the issue with toolbox, that was my bad, and I had to add two more translations.

`  
"Zone Controls:": "Commandes de zone:",
"Splines:": "Splines:",
`

**Comment by MacNaab** [comment] 2020-11-16 18:48
Good news! When appetite goes, anything goes!
``` JSON
   "Just Nodes": "Seulement le nœud",
   "Zone Controls:": "Commandes de zone:",
   "Splines:": "Détourages",
```
Yeah I found it ! (it's also not translated in my side)
![image](https://user-images.githubusercontent.com/61412526/99294259-1cbd7e80-2844-11eb-8c8d-92218ef781fa.png)

I'm gonna try on another computer!
Update: Didn't work on W8 and W10

**Comment by Bonkahe** [comment] 2020-11-16 19:03
Just to be 100% sure try the latest update, I doubt it will fix it but let's rule out that possibility.

Edit: Also do ANY of the pop ups translate properly? could you give me a list of all the ones you find that do/don't?

Edit2: A note on the character generator, the buttons are procedural created with the content of a spreadsheet, as such hard coding a translation is impossible... might have to live with the current state of that.

**Comment by MacNaab** [comment] 2020-11-16 19:37
It's the same with the last update.
ATM there are only the elements of the previous message, but maybe I didn't have all the pops up.

Yeah, I suspected it, but to be honest, I don't use it (I don't play on dnd5)

**Comment by Bonkahe** [comment] 2020-11-16 20:55
I mostly use it for quick descriptions, and names, the name generator is pretty solid with the region selector changing the origin of the name... bits, idk it pieces together new names from sounds.

**Comment by MacNaab** [comment] 2020-11-16 21:09
Maybe I'll use it in that case, I'm playing on The Witcher TRPG btw.

**Comment by Bonkahe** [comment] 2020-11-16 21:12
Lol I recognized some of the countries in your past images ;) I am a big fan of the world.

**Comment by MacNaab** [comment] 2020-11-17 06:15
Awesome! Since it's a totally different system, I created my own generators, but indeed, it's really interesting for the names.

Where is the translation file stored? I would improve it as I use this programme.

**Comment by Bonkahe** [comment] 2020-11-17 12:21
Unfortunately electron packs all that in hardcoded, but if you look at the directory in the git repo itself you can see it in the translations folder, id you want you could fork the repo and if you have any changes you make you can do a merge request, I'd be 100% down to ok it.

I'm still stumped by the popups not working though, as soon as I have time I need to sit down and see if I can figure out why, btw there's no errors right? just incorrect functioning?

**Comment by MacNaab** [comment] 2020-11-17 13:46
That's what I'm going to do then!

Yep, no error in logs.
Another person has downloaded the application and he has everything in French, so maybe it's just me? (But on 2 computer..)

**Comment by Bonkahe** [comment] 2020-11-17 14:02
Hmmm try uninstalling and deleting this folder: `C:\Users\[your username]\AppData\Roaming\dmmaps` Then reinstall freshly from the release, beyond that I have no idea, be aware this will lose your theme changes.

**Comment by MacNaab** [comment] 2020-11-17 16:56
Unfortunately that didn't change anything.   
Edit: I've add the fork
I just noticed that the translation of "Search Titles" is missing in the fr.json and "Enable fill of region." is still in english (but he is translate in fr.json).

**Comment by Bonkahe** [comment] 2020-11-17 18:26
No idea about the errors then, something having to do with your specific system I suppose... I will continue searching for answers on google.
I merged your fork, fixed the translation of enable fill of region and added search tiles/search contents.
Also implemented several other quality of life fixes, see release notes for full break down.

**Comment by MacNaab** [comment] 2020-11-17 18:30
If it's just me no problems with that 👌
Nice! Good job, I gonna check that

**Comment by Bonkahe** [comment] 2020-11-23 18:59
Hey! so in the latest update there is compression support for the packed mode, and there are some more translations that came up, was wondering if you had a moment if you could look over the translations:

```
  "Copy": "Copie",
  "Paste": "Pâte",

  "Disable Auto Compression": "Désactiver la compression automatique",
  "Enable Auto Compression": "Activer la compression automatique",

  "If you do this, all images packed into the database will be clamped down to the given resolution, this is permanent. Are you sure?": "Si vous faites cela, toutes les images contenues dans la base de données seront réduites à la résolution donnée, ceci est permanent. Êtes-vous sûr?",
  "This will clamp all images resolution based off the width, the height will scale accordingly, input into the field the width you would like to use, and enable compression.": "Cela limitera la résolution de toutes les images en fonction de la largeur, la hauteur sera mise à l'échelle en conséquence, saisira dans le champ la largeur que vous souhaitez utiliser et activera la compression.",
```

**Comment by MacNaab** [comment] 2020-11-23 19:36
Hey, sure:
``` JSON
 "Copy": "Copier",
  "Paste": "Coller",

  "Disable Auto Compression": "Désactiver la compression automatique",
  "Enable Auto Compression": "Activer la compression automatique",

  "If you do this, all images packed into the database will be clamped down to the given resolution, this is permanent. Are you sure?": "Si vous faites cela, toutes les images contenues dans la base de données seront réduites à la résolution donnée, ceci est permanent. Êtes-vous sûr?",
  "This will clamp all images resolution based off the width, the height will scale accordingly, input into the field the width you would like to use, and enable compression.": "Cela limitera la résolution de toutes les images en fonction de la largeur, la hauteur sera mise à l'échelle en conséquence, saisissez dans le champ la largeur que vous souhaitez utiliser et activer la compression.",
```

**Comment by Bonkahe** [comment] 2020-11-23 20:08
Thank you so much!

I'm working on multi select features as well as a patch notes window which pops up after an update, after that we might be nearing 1.0 :>

**Comment by MacNaab** [comment] 2020-11-23 20:41
Can't wait to see what it will do! I made a [video presentation](https://youtu.be/QyB6X1hadaY) of your app but I would probably do one again at 1.0 😃

**Comment by Bonkahe** [comment] 2020-11-27 04:31
Lots of new features, also three more translations xP any chance you could have a look at them?

```
  "Custom Distance Label:": "Étiquette de distance personnalisée:",
  "Would you like to paste documents as well?": "Souhaitez-vous également coller des documents?",
  "The documents will be places directly next to their originals.": "Les documents seront placés directement à côté de leurs originaux.",
```

**Comment by MacNaab** [comment] 2020-11-27 10:22
Hey ! Sure:
```
 "Custom Distance Label:": "Distance personnalisée:",
  "Would you like to paste documents as well?": "Souhaitez-vous également coller les documents?",
  "The documents will be places directly next to their originals.": "Les documents seront placés directement à côté de leurs originaux.",
```
Could I have the context of the first one? (or how to get it)
Edit:  It must also be missing:
```
"Display Patch Notes": "Afficher la note de la MaJ",
"Copy paste options": "Options de copier-coller",
"Reset Document/Node only paste option.": "Réinitialiser l'option Coller le document/nœud uniquement.",
```

**Comment by Bonkahe** [comment] 2020-11-27 14:16
It's on the options menu, but it's a label for the entry field where you can put in custom distance measurement names, to be used for measuring, like for example you can type in Days, and now when you use the measuring tool it will measure in days instead of miles/kilometers etc.
And thank you again, this won't be in the next little bug fix but the one right after.

**Comment by MacNaab** [comment] 2020-11-27 18:44
Ah yes I just found it! Therefore the translation would be rather
```
 "Custom Distance Label:": "Unité de distance personnalisée:",
```
I also noticed that in the option menu there is always : `"Copy paste options:"`

**Comment by Bonkahe** [comment] 2021-06-05 16:06
I'm gonna go ahead and close this for now, this will need more work in the future, but for now it's passable.

**Closed as completed by Bonkahe** 2021-06-05 16:06 UTC
Labels: enhancement
